### ISSUE TITLE
Windows exe for community, to equal farm for all

### ISSUE THREAD

**Issue by Jason20101981** [MintNetwork/mint-blockchain#10]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**
Please complete the following information.

- OS: e.g. Linux
- OS Version/Flavor: e.g. CentOS 7.2
- CPU: e.g. Intel Xeon 8175M

**Additional context**

**Comment by JacobMackenzie** [comment]
Windows-installer build is ready
