### ISSUE TITLE
Mint ports collide with other forks

### ISSUE THREAD

**Issue by rwarren** [MintNetwork/mint-blockchain#7]
Your chosen ports have some issues.  Please see the overall chia fork port map here for details:
https://docs.google.com/spreadsheets/d/1ttIK-TQwwWeY4XarapjKAYJIgDJ5Kk9yjvBPLIlrpdg/edit#gid=1006768047

![image](https://user-images.githubusercontent.com/2751728/130691116-ed14217c-7514-4cce-ae5f-a62695ec7407.png)

**Comment by littlestone** [comment]
Thanks for the info, the ports have been updated accordingly to avoid the collision with other forks.

**Comment by littlestone** [comment]
> Your chosen ports have some issues. Please see the overall chia fork port map here for details:
> https://docs.google.com/spreadsheets/d/1ttIK-TQwwWeY4XarapjKAYJIgDJ5Kk9yjvBPLIlrpdg/edit#gid=1006768047
> 
> ![image](https://user-images.githubusercontent.com/2751728/130691116-ed14217c-7514-4cce-ae5f-a62695ec7407.png)

FYI, we have updated all ports beginning with 29 instead of 19, thanks!
