### ISSUE TITLE
Introducer / peers

### ISSUE THREAD

**Issue by bithadder** [MintNetwork/mint-blockchain#9]
Hi, the introducer doesn't work and there's no peers to connect to

**Comment by ageorge95** [comment]
I would also like some nodes, please.

**Comment by JacobMackenzie** [comment]
Still on qa stage, Mainnet will be launched soon.

**Comment by ageorge95** [comment]
@JacobMackenzie will the "mainnet" reset the chain ?

**Comment by littlestone** [comment]
@ageorge95 yes, the "mainnet" will be reset upon official announced launch time.
